---
name: Build Container

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: docker version
    - run: pwd
    - run: ls -la
    - run: >
        docker build -t ${image_name}:${regexr_version} --file base.dockerfile
        --build-arg REGEXR_VERSION=${regexr_version}
        --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        .
      env:
        image_name: winkelchri/regexr-base
        regexr_version: "3.6.1"

    # - run: python3 build.py
