---
name: Build Container

on: push

jobs:
  build:
    name: Build regexr image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build regexr image
      id: build
      run: echo "##[set-output name=version;]$(python3 build.py --skip-build)"

    - name: Output regexr image tag
      run: |
        echo "The tag was ${{ steps.build.outputs.version }}"

  push:
    name: Push regexr image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Show docker images
        run: |
          docker images

  #   - name: Push image to Dockerhub
  #     run: |
  #       echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  #       docker push winkelchri/regexr:latest
