---
name: Build Container

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Build regexr image
      run: python3 build.py

    - name: Push image to Dockerhub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push winkelchri/regexr:latest
