---
name: Build Container

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: docker version
    - run: pwd
    - run: ls -la
    # - run: python3 build.py
